# Generated by Django 4.1.4 on 2022-12-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yelpuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
